Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Simulation = fdsreader.Simulation('./non-predefined_fuel/')

time = Simulation.slices[0].get_nearest_timestep(3)

plt.imshow(Simulation.slices[0][0].data[time].T, 
               origin = 'lower', 
               extent = Simulation.slices[0].extent.as_list())
        
plt.title('Pentane')
plt.xlabel("x / m")
plt.ylabel("z / m")
plt.colorbar(label = "Mass Fraction")
        
plt.savefig("figs/mass_frac_pentane.svg")
plt.close()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m<ipython-input-2-cda763352c54>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mSimulation[0m [0;34m=[0m [0mfdsreader[0m[0;34m.[0m[0mSimulation[0m[0;34m([0m[0;34m'./non-predefined_fuel/'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mtime[0m [0;34m=[0m [0mSimulation[0m[0;34m.[0m[0mslices[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m.[0m[0mget_nearest_timestep[0m[0;34m([0m[0;36m3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m plt.imshow(Simulation.slices[0][0].data[time].T, 

[0;32m/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/fdsreader/simulation.py[0m in [0;36m__new__[0;34m(cls, path)[0m
[1;32m     54[0m     [0;32mdef[0m [0m__new__[0m[0;34m([0m[0mcls[0m[0;34m,[0m [0mpath[0m[0;34m:[0m [0mstr[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     55[0m         [0;32mif[0m [0msettings[0m[0;34m.[0m[0mENABLE_CACHING[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 56[0;31m             [0msmv_file_path[0m [0;34m=[0m [0mget_smv_file[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     57[0m             [0mroot_path[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mdirname[0m[0;34m([0m[0msmv_file_path[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     58[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/fdsreader/utils/data.py[0m in [0;36mget_smv_file[0;34m(path)[0m
[1;32m    108[0m         [0;32mreturn[0m [0mpath[0m [0;34m+[0m [0;34m".smv"[0m[0;34m[0m[0;34m[0m[0m
[1;32m    109[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 110[0;31m         [0;32mraise[0m [0mIOError[0m[0;34m([0m[0;34m"Path is invalid!"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    111[0m [0;34m[0m[0m
[1;32m    112[0m [0;34m[0m[0m

[0;31mOSError[0m: Path is invalid!
OSError: Path is invalid!

